bug: fix-the-hover-effect-in-button
bluewave-labs/checkmate pull request #1346
Opened 2024-12-10 17:56 UTC by theanuragg

### what does this PR do ?

- Resolves the hover effect issue for the button.
- Updated hover color for the light theme to **#912018.**

fix #1335

**Changes Made**

- Adjusted the hover styles in the button component.
- Added conditional hover behavior based on the light/dark theme mode.

2024-12-10 18:32 UTC, theanuragg commented
@ajhollid hey

2024-12-10 19:14 UTC, gorkem-bwl commented
Please send a video for this. Thanks!

2024-12-11 02:01 UTC, ajhollid requested changes
Hi @theanuragg ,

Thanks for taking the time to contribute to the project!

This solution is a bit to literal however, it is only applied to the one `Button`, moreover there is no difference between hover and regular state now, they are both `#D32F2F`

If you'd like to work on this issue further then the change must be applied to _all_ buttons, which means working with the theme file instead of individual buttons.

2024-12-11 02:02 UTC, ajhollid commented on Client/src/Pages/Settings/index.jsx
> +											: theme.palette.error.dark,
These colors don't match the desing spec in #1335, they should aslo apply to all buttons, not just this specific one

2024-12-11 02:05 UTC, ajhollid commented
I'll close this PR for now as it doesn't address the root issue.

Thanks for taking the time to submit a fix, it's not quite on target though.

2024-12-11 02:05 UTC, closed without merging