Reset password link should be present in all pages #1403
bluewave-labs/checkmate pull request #1406
Opened 2024-12-15 18:00 UTC by Anand-Royy

Reset password link is added to all the login pages.

2024-12-15 19:40 UTC, gorkem-bwl commented
Can you please send a screenshot showing those pages?

2024-12-15 19:55 UTC, gorkem-bwl commented
> Sure
> 
Great, thanks. I believe the light theme looks ok on your end, right? Can you check that too? 

For my info - there should have been a PR template when you issue this PR. Did you see it? I am not sure if that is in action. 

It should have looked something like this:

![image](https://github.com/user-attachments/assets/5b4f780c-8dbd-40e1-abaa-99dd2c14e94a)

2024-12-15 20:03 UTC, Anand-Royy commented
>Great, thanks. I believe the light theme looks ok on your end, right? Can you check that too?

Yes, the light theme is also fine. 

![image](https://github.com/user-attachments/assets/80d61326-3705-4e66-9754-19410ca65431)

![image](https://github.com/user-attachments/assets/e0a07f5c-58d3-444c-b8be-d2782598ded0)

2024-12-15 20:04 UTC, Anand-Royy commented
>For my info - there should have been a PR template when you issue this PR. Did you see it? I am not sure if that is in action.

Ok, I'll add it

2024-12-15 20:07 UTC, gorkem-bwl commented
> > For my info - there should have been a PR template when you issue this PR. Did you see it? I am not sure if that is in action.
> 
> Ok, I'll add it

OK. It's important you do not remove it next time. It's meant to be filled in properly.

2024-12-15 20:19 UTC, Anand-Royy commented
> OK. It's important you do not remove it next time. It's meant to be filled in properly.

I have added it. Please check.

2024-12-16 01:17 UTC, Samsonbtc247 commented on Client/src/Pages/Auth/Login.jsx
> +				</Box>
> _:bulb: Codebase verification_
> 
> _:hammer_and_wrench: Refactor suggestion_
> 
> **Yo! The review's on point - this Box needs some serious refactoring!**
> 
> Looking at the code, I found the same Box component with identical styling being used in three places within Login.jsx (in LandingPage, StepOne, and StepTwo components). The Box contains the same "Forgot password?" and "Reset password" text with identical positioning and styling.
> 
> - `Client/src/Pages/Auth/Login.jsx`: The Box component is duplicated in:
>   - LandingPage component (around line 247)
>   - StepOne component (around line 419)
>   - StepTwo component (around line 544)
> 
> The suggested ResetPasswordLink component would indeed help eliminate this duplication and improve accessibility with the added keyboard navigation support.
> 
> 
> 
> <details>
> <summary>🔗 Analysis chain</summary>
> 
> **Yo! Extract this Box component to reduce duplication**
> 
> This Box component is copy-pasted in multiple places. Let's keep it DRY!
> 
> ```diff
> +const ResetPasswordLink = ({ handleNavigate }) => {
> +  const theme = useTheme();
> +  return (
> +    <Box
> +      textAlign="center"
> +      sx={{
> +        position: "absolute",
> +        bottom: 0,
> +        left: "50%",
> +        transform: `translate(-50%, 150%)`,
> +      }}
> +    >
> +      <Typography
> +        className="forgot-p"
> +        display="inline-block"
> +        color={theme.palette.primary.main}
> +      >
> +        Forgot password?
> +      </Typography>
> +      <Typography
> +        component="span"
> +        color={theme.palette.primary.main}
> +        ml={theme.spacing(2)}
> +        sx={{ 
> +          userSelect: "none",
> +          cursor: "pointer",
> +          "&:focus": {
> +            outline: `2px solid ${theme.palette.primary.main}`,
> +            outlineOffset: "2px"
> +          }
> +        }}
> +        role="link"
> +        tabIndex={0}
> +        onKeyPress={(e) => e.key === 'Enter' && handleNavigate()}
> +        onClick={handleNavigate}
> +      >
> +        Reset password
> +      </Typography>
> +    </Box>
> +  );
> +};
> 
> +ResetPasswordLink.propTypes = {
> +  handleNavigate: PropTypes.func.isRequired,
> +};
> ```
> 
> </details>
> 
> <details>
> <summary>🏁 Scripts executed</summary>
> 
> The following scripts were executed for the analysis:
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Check for similar Box components in other files
> rg -l 'Forgot password.*Reset password' --type jsx
> 
> ```
> 
> Length of output: 80
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Let's try with a different approach to find similar Box components
> rg -U "Box.*position.*absolute.*bottom.*left.*transform.*translate.*Forgot password" --type ts --type tsx --type js --type jsx
> 
> ```
> 
> Length of output: 156
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Search for files containing both "Forgot password" and "Reset password"
> rg -l "Forgot password" --type ts --type tsx --type js --type jsx
> 
> ```
> 
> Length of output: 95
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Let's also check for any Box components with similar positioning
> rg -U "Box.*position.*absolute.*bottom.*left.*transform.*translate" --type ts --type tsx --type js --type jsx
> 
> ```
> 
> Length of output: 139
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Let's try without file type restrictions
> rg -U "Box.*position.*absolute.*bottom.*left.*transform.*translate.*Forgot password"
> 
> ```
> 
> Length of output: 86
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Search for files containing both phrases without type restrictions
> rg -l "Forgot password"
> 
> ```
> 
> Length of output: 171
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Find all potential React/JS/TS files
> fd -e js -e jsx -e ts -e tsx
> 
> ```
> 
> Length of output: 9378
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Let's check the content of ForgotPassword.jsx and Login.jsx for similar Box components
> cat "Client/src/Pages/Auth/ForgotPassword.jsx" "Client/src/Pages/Auth/Login.jsx"
> 
> ```
> 
> Length of output: 20642
> 
> ---
> 
> Script:
> 
> ```shell
> #!/bin/bash
> # Let's also check if there are any other similar Box components with absolute positioning
> rg -U "Box.*textAlign.*position.*absolute" Client/src/Pages/Auth/
> 
> ```
> 
> Length of output: 67
> 
> </details>
> 
> <!-- This is an auto-generated comment by CodeRabbit -->

#1403

2024-12-16 19:07 UTC, ajhollid requested changes
Hi @Anand-Royy ,

Thanks for your contribution here!

A recent PR has moved the `Login.jsx` file to `/Auth/Login/Login.jsx`, the `/Auth/Login.jsx` page no longer exists.

Could you please either merge `develop` into your feature branch and move your changes to `/Auth/Login/Login.jsx` or just close this PR and move the changes to a new branch from develop?

Thanks!

2024-12-17 01:25 UTC, ajhollid commented
It looks like you've just copied your `Login.jsx` and pasted it over the most recent version of `/Auth/Login/Login.jsx`.  

That will overwrrite all the changes made in recent PRs.

I'm going to close this PR as this is not mergeable, if you'd like to commit the code for adding the reset password link the steps to follow are

1.  Checkout `develop` remote branch
2. Create a new branch from the current state of `develop`
3. Make your changes, commit, and push.

2024-12-17 18:40 UTC, Anand-Royy commented
Hi @ajhollid, I pulled the changes from the `develop` branch and I could find the `/Auth/Login/Login.jsx` file. But when I make changes to this file or the files inside the `/Auth/Login/Component`, I can't see any changes being reflected to the frontend. 

Also I can still see the previous `login.jsx` file outside the `Login` folder and when I make changes to this file then I can see the changes getting reflected on the frontend too. Is this supposed to happen?

2024-12-17 18:43 UTC, ajhollid commented
@Anand-Royy I can't really troubleshoot your repository for you remotely, my suggestion to quickly get back on track is just reclone the repository.

Any other Git troubleshooting you'll have to handle on your end.

2024-12-17 18:51 UTC, Anand-Royy commented
>A recent PR has moved the Login.jsx file to /Auth/Login/Login.jsx, the /Auth/Login.jsx page no longer exists.

@ajhollid I can see both the files in the repo

![image](https://github.com/user-attachments/assets/9249d7fa-7893-4f74-87bc-da43b58661a1)

2024-12-17 18:56 UTC, Anand-Royy commented
@ajhollid Yes, so the changes made to the file `/Auth/Login.jsx` is actually reflecting to the frontend and not the file changes made in `/Auth/Login/Login.jsx`. Please check this because my local repo is updated with the latest commit in the remote branch and I can observe these changes.

2024-12-17 21:13 UTC, ajhollid commented
Hi @Anand-Royy ,

You are correct, the old page was being rendered by the router.  I have removed the old page and corrected the route, you can make a new PR with your changes in the `/Auth/Login/Login.jsx` page if you'd like.

Thanks!

2024-12-18 17:43 UTC, closed without merging