Red button mouse hover status has wrong color #1335
bluewave-labs/checkmate pull request #1472
Opened 2024-12-26 08:26 UTC by Anand-Royy

## Describe your changes
Changed the colour property of hover

## Issue Number
#1335 

## Please ensure all items are checked off before requesting a review:
- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I have labelled the PR correctly.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached this to PR if there is a UI change.

## Video

https://github.com/user-attachments/assets/dd18a367-c725-4014-bb1a-06d51014bf00

2024-12-26 13:28 UTC, gorkem-bwl commented
Looks good @Anand-Royy - can you also please send a video / screenshot of how it looks for the dark theme as well?

2024-12-26 15:24 UTC, Anand-Royy commented
@gorkem-bwl please check

https://github.com/user-attachments/assets/35ab24de-1423-4906-a005-06bb0141c120

2024-12-26 18:00 UTC, gorkem-bwl commented
Looks good!

2024-12-26 20:13 UTC, ajhollid requested changes
red50 and red800 are the same colors, this is semantically incorrect even if the colors display properly :thinking: 

What is trying ot be achieved her by setting the two colors to be the same value?

2024-12-26 20:13 UTC, ajhollid commented on Client/src/Utils/Theme/constants.js
> +	red800: "#912018",
Why are red50 and red800 the same colors?

2024-12-29 16:59 UTC, ajhollid approved these changes
Thanks, looks good and makes more sense now!

2024-12-29 16:59 UTC, merged