added a star repo modal
bluewave-labs/checkmate pull request #1492
Opened 2024-12-29 20:19 UTC by dikjain

I have fixed the #1484 issue by adding a star repo modal 

here is how it looks :
![Screenshot 2024-12-30 014420](https://github.com/user-attachments/assets/66b35aa8-07d6-4d9f-90a6-2954e1e6b377)

fixed #1484

2024-12-29 20:35 UTC, gorkem-bwl commented
> I have fixed the #1484 issue by adding a star repo modal
> 
> fixed #1484

Thank you for your contribution.

This has already been assigned and probably the developer is working on it. You can remove your PR for now and wait for a couple of days for the assigned developer to see if it's resolved. Sorry about that.

2024-12-29 20:57 UTC, mertssmnoglu commented on package-lock.json
Hi Dikshit! Thanks for your effort.

Since the Client and Server has separate dependencies in their directories we don't need `package-lock.json` file in the root directory. I think it comes from wrongly used `npm install` command, you can remove it.

2024-12-31 18:11 UTC, ajhollid requested changes
Please remove all hardcoded values and the `package-lock.json` file in the root directory.

Thank you!

2024-12-31 18:11 UTC, ajhollid commented on Client/src/Components/Sidebar/index.jsx
> +					<Typography style={{  fontSize: "13px" , marginTop: "10px" , color: "black"  }} variant="body2" color="black">
Hardcoded values, especially font sizes and colors, are inhernetly not maintainable.

Please refactor to make use of the theme.

2024-12-31 18:11 UTC, ajhollid commented on package-lock.json
Indeed, please remove this `pacakge-lock.json` file.

2025-01-02 17:52 UTC, ajhollid commented
Closing this PR as inactive

2025-01-02 17:52 UTC, closed without merging